version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/src

  db:
    image: postgres:13.3
    environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=user
    volumes:
        - service-data:/var/lib/postgresql/data


volumes:
    service-data: