version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/src

  db:
    image: postgres:13.3
    environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=user
    volumes:
        - service-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5452:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pass
    logging:
      driver: none

volumes:
    service-data: