"""add transfer date field

Revision ID: a60c72aa405b
Revises: 38b4a2097cb5
Create Date: 2021-10-21 16:29:13.114663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60c72aa405b'
down_revision = '38b4a2097cb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('transfer_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'transfer_date')
    # ### end Alembic commands ###
