"""create offer table

Revision ID: 96b4e6ee111d
Revises: 
Create Date: 2021-11-05 09:40:25.733359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b4e6ee111d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('CANCELED', 'PENDING', 'ACCEPTED', 'TRANSFERRED', name='offerstatus'), nullable=True),
    sa.Column('task_id', sa.String(length=128), nullable=True),
    sa.Column('accept_date', sa.DateTime(), nullable=True),
    sa.Column('transfer_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    # ### end Alembic commands ###
