"""add task_id field

Revision ID: fb0e6db78ec9
Revises: cc70436e2537
Create Date: 2021-11-04 15:38:15.088048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0e6db78ec9'
down_revision = 'cc70436e2537'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('task_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'task_id')
    # ### end Alembic commands ###
