"""add fields accepted, accept_date

Revision ID: 34bda02e6e46
Revises: 9c7a34d6fb58
Create Date: 2021-10-23 21:08:21.657502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34bda02e6e46'
down_revision = '9c7a34d6fb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('accepted', sa.Boolean(), nullable=True))
    op.add_column('offer', sa.Column('accept_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'accept_date')
    op.drop_column('offer', 'accepted')
    # ### end Alembic commands ###
